name: Retrain Model Weekly

on:
  schedule:
    - cron: '45 1 * * 1'  # setiap hari Senin pukul 08:45 WIB (01:45 UTC)
  workflow_dispatch:       # bisa dijalankan manual juga

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run model training
        run: |
          python train_model.py

      - name: Commit and push retrained model
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add random_forest_model.pkl
          git commit -m "🔁 Weekly retrain model (auto)"
          git push
