name: Daily Stock Signal Scanner

on:
  schedule:
    - cron: '45 1 * * *' # UTC 01:45 = 08:45 WIB
  push:
      branches:
        - main
  workflow_dispatch:

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          pip install yfinance pandas ta requests python-telegram-bot
      
      - name: Run Scanner Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python scanner_bot.py
    
